language: c
compiler: gcc
sudo: false
cache: ccache

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

script:
  - tests/scripts/all.sh -k test_default_out_of_box
  - tests/scripts/all.sh -k test_build_opt
  - tests/scripts/all.sh -k test_full_cmake_gcc_asan
  - tests/scripts/all.sh -k test_m32_o1

after_failure:
- tests/scripts/travis-log-failure.sh

env:
  global:
    - SEED=1
    - secure: "FrI5d2s+ckckC17T66c8jm2jV6i2DkBPU5nyWzwbedjmEBeocREfQLd/x8yKpPzLDz7ghOvr+/GQvsPPn0dVkGlNzm3Q+hGHc/ujnASuUtGrcuMM+0ALnJ3k4rFr9xEvjJeWb4SmhJO5UCAZYvTItW4k7+bj9L+R6lt3TzQbXzg="

addons:
  apt:
    packages:
    - gnutls-bin
  coverity_scan:
    project:
      name: "ARMmbed/mbedtls"
    notification_email: support-mbedtls@arm.com
    build_command_prepend:
    build_command: make
    branch_pattern: coverity_scan
